version: '3.8'

volumes:
  data:

networks:
  backend:

services:

  back:
    container_name: back
    build: ./backend/
    volumes:
      - ./backend:/app
    #working_dir: /app
    ports:
      - 4000:4000
    #command: sh -c "npm install && npm run start:dev"
    #command: tail -f /dev/null
    restart: unless-stopped
    networks:
      - backend
    depends_on:
      - postgres

  front:
    container_name: front
    build: ./frontend/
    volumes:
      - ./frontend:/app
#    working_dir: /app
    ports:
      - 3000:3000
    #command: tail -f /dev/null
    #command: sh -c "npm install && npm run start"
    networks:
     - backend
    restart: unless-stopped
    depends_on:
      - backend
  
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    ports:
      - 5432:5432
    restart: unless-stopped
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=prisma
      - POSTGRES_DB=dbdata
    networks:
    - backend

# add nginx reverse proxy using previous setup
